pipeline {
    agent any
    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'staging', 'prod'], description: 'Deployment environment')
        string(name: 'HELM_CHART', defaultValue: 'oci://registry-1.docker.io/bitnamicharts/mlflow', description: 'Helm chart')
        string(name: 'VALUES_FILE', defaultValue: './values/values.yml', description: 'Archivo de valores por entorno')
        string(name: 'IMAGE_TAG', defaultValue: '2.19.0-debian-12-r0', description: 'Image tag')
        choice(name: 'DEFAULT_PERMISSION', choices: ['NO_PERMISSION', 'MANAGE'], description: 'Default permission for all users')
        string(name: 'INGRESS_ENDPOINT', defaultValue: 'mlflow.dev.k8s.synthema.rid-intrasoft.eu', description: 'Endpoint URL for external access')
        choice(name: 'EXTERNAL_DB_HOST', choices: ['mstorage-svc.synthema-dev', 'metadata-storage.synthema-staging'])
        choice(name: 'EXTERNAL_DB_DBNAME', choices: ['mlflow'])
        choice(name: 'EXTERNAL_DB_AUTHDBNAME', choices: ['mlflow_auth'])
        choice(name: 'EXTERNAL_S3_HOST', choices: ['obstorage-minio.synthema-dev', 'metadata-storage.synthema-staging'])
        choice(name: 'EXTERNAL_S3_BUCKET_NAME', choices: ['mlflow'])
    }
    environment {
        ADMIN_CREDENTIALS_ID = "admin-${params.ENVIRONMENT}"
        DB_CREDENTIALS_ID = "db-${params.ENVIRONMENT}"
        S3_CREDENTIALS_ID = "s3_keyid-secret-${params.ENVIRONMENT}"
    }
    stages {
        stage('Setup Environment') {
            steps {
                withCredentials([
                    usernamePassword(credentialsId: "${env.ADMIN_CREDENTIALS_ID}", usernameVariable: 'ADMIN_USERNAME', passwordVariable: 'ADMIN_PASSWORD'),
                    usernamePassword(credentialsId: "${env.DB_CREDENTIALS_ID}", usernameVariable: 'DB_USERNAME', passwordVariable: 'DB_PASSWORD'),
                    string(credentialsId: "${env.S3_CREDENTIALS_ID}", variable: 'S3_KEY_SECRET_PAIR')
                ]) {
                    script {
                        def s3_keyIdSecret = S3_KEY_SECRET_PAIR.split(':')
                        env.S3_ACCESS_KEY_ID = s3_keyIdSecret[0]
                        env.S3_ACCESS_KEY_SECRET = s3_keyIdSecret[1]
                    }
                }
            }
        }
        stage('Verify Values') {
            steps {
                script {
                    echo "Verifying values..."
                    sh """
                    helm template ${params.ENVIRONMENT}-release ${params.HELM_CHART} \
                        --namespace synthema-${params.ENVIRONMENT} \
                        --values ${params.VALUES_FILE} \
                        --set image.tag=${params.IMAGE_TAG} \
                        --set tracking.auth.username=${env.ADMIN_USERNAME} \
                        --set tracking.auth.password=${env.ADMIN_PASSWORD} \
                        --set tracking.auth.extraOverrides.default_permission=${params.DEFAULT_PERMISSION} \
                        --set tracking.ingress.hostname=${params.INGRESS_ENDPOINT} \
                        --set externalDatabase.user=${env.DB_USERNAME} \
                        --set externalDatabase.password=${env.DB_PASSWORD} \
                        --set externalDatabase.host=${params.EXTERNAL_DB_HOST} \
                        --set externalDatabase.database=${params.EXTERNAL_DB_DBNAME} \
                        --set externalDatabase.authDatabase=${params.EXTERNAL_DB_AUTHDBNAME} \
                        --set externalS3.host=${params.EXTERNAL_S3_HOST} \
                        --set externalS3.accessKeyID=${env.S3_ACCESS_KEY_ID} \
                        --set externalS3.accessKeySecret=${env.S3_ACCESS_KEY_SECRET} \
                        --set externalS3.bucket=${params.EXTERNAL_S3_BUCKET_NAME}
                    """
                }
            }
        }
        stage('Deploy with Helm') {
            steps {
                script {
                    echo "Deploying..."
                    sh """
                    helm upgrade --install ${params.ENVIRONMENT}-release ${params.HELM_CHART} \
                        --namespace synthema-${params.ENVIRONMENT} \
                        --values ${params.VALUES_FILE} \
                        --set image.tag=${params.IMAGE_TAG} \
                        --set tracking.auth.username=${env.ADMIN_USERNAME} \
                        --set tracking.auth.password=${env.ADMIN_PASSWORD} \
                        --set tracking.auth.extraOverrides.default_permission=${params.DEFAULT_PERMISSION} \
                        --set tracking.ingress.hostname=${params.INGRESS_ENDPOINT} \
                        --set externalDatabase.user=${env.DB_USERNAME} \
                        --set externalDatabase.password=${env.DB_PASSWORD} \
                        --set externalDatabase.host=${params.EXTERNAL_DB_HOST} \
                        --set externalDatabase.database=${params.EXTERNAL_DB_DBNAME} \
                        --set externalDatabase.authDatabase=${params.EXTERNAL_DB_AUTHDBNAME} \
                        --set externalS3.host=${params.EXTERNAL_S3_HOST} \
                        --set externalS3.accessKeyID=${env.S3_ACCESS_KEY_ID} \
                        --set externalS3.accessKeySecret=${env.S3_ACCESS_KEY_SECRET} \
                        --set externalS3.bucket=${params.EXTERNAL_S3_BUCKET_NAME}
                    """
                }
            }
        }
    }
}